(()=>{'use strict';const en=document.documentElement.lang==='en',prefix=en?'/en/':'/';const t=(fa,eng)=>en?eng:fa;
const serviceNames={metal:['ساخت قطعات فلزی','Metal component manufacturing'],polymer:['ساخت قطعات پلیمری','Polymer components'],composite:['ساخت قطعات کامپوزیتی','Composite fabrication'],sports:['تجهیزات ورزشی سفارشی','Custom sports equipment'],design:['طراحی و بررسی مسیر ساخت','Design & manufacturing review'],'3d-printing':['نمونه‌سازی با پرینت سه‌بعدی','3D printing & prototyping']};
const related={metal:'couplings',polymer:'printed-fan',composite:'composite-fan',sports:'portable-mini-golf',unsure:'cable-reel'};
const goals={sample:['ساخت از روی نمونه','Manufacture from an existing sample'],drawing:['ساخت از روی نقشه یا مدل','Manufacture from a drawing or model'],idea:['طراحی از روی ایده','Develop an idea'],prototype:['نمونه‌سازی پیش از تولید','Prototype before production']};
const materials={metal:['فلزی','Metal'],polymer:['پلیمری','Polymer'],composite:['کامپوزیتی','Composite'],sports:['تجهیزات ورزشی','Sports equipment'],unsure:['جنس / حوزه هنوز مشخص نیست','Material / category to be discussed']};
const volumes={single:['یک قطعه یا نمونه','A single part or sample'],batch:['تولید سری؛ تعداد دقیق نیاز به اعلام دارد','Batch production; exact quantity to be specified'],unknown:['تعداد نیاز به بررسی دارد','Quantity to be discussed']};
function valid(o){return Object.hasOwn(goals,o.goal)&&Object.hasOwn(materials,o.material)&&Object.hasOwn(volumes,o.volume)}
const form=document.querySelector('#route-form');if(form){const result=document.querySelector('#route-result');form.addEventListener('change',()=>{result.hidden=true});form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const o=Object.fromEntries(new FormData(form));if(!valid(o))return;let service=o.material==='unsure'?'design':o.material;if(o.goal==='idea')service='design';if(o.goal==='prototype')service=['polymer','unsure'].includes(o.material)?'3d-printing':'design';document.querySelector('#route-title').textContent=serviceNames[service][en?1:0];const descriptions={sample:t('ابعاد و کاربرد نمونه، جنس و سطوح اتصال را برای بررسی آماده کنید.','Prepare the sample dimensions, application, material and connection interfaces for review.'),drawing:t('نقشه یا مدل، واحد اندازه‌گیری، ابعاد حساس و جنس پیشنهادی را همراه درخواست بفرستید.','Include your drawing or model, measurement units, critical dimensions and proposed material.'),idea:t('شرح کاربرد و محدودیت‌های محصول را مشخص کنید؛ طراحی و انتخاب روش ساخت، نقطهٔ شروع گفت‌وگو است.','Describe the application and product constraints. Design and process selection are the starting point.'),prototype:t('مشخص کنید نمونه برای بررسی شکل، مونتاژ یا عملکرد است؛ روش نمونه‌سازی باید با این هدف تطبیق داده شود.','Tell us whether the prototype is for form, fit or function. The prototyping route must match that purpose.')};document.querySelector('#route-description').textContent=descriptions[o.goal]+' '+volumes[o.volume][en?1:0]+'.';const a=document.querySelector('#route-service');a.href=prefix+'services/'+service+'.html';a.textContent=t('آشنایی با این خدمت ↗','Explore this capability ↗');const p=document.querySelector('#route-project');p.href=prefix+'projects/'+related[o.material]+'.html';p.textContent=t('مشاهده یک نمونه‌کار ↗','View a project example ↗');const params=new URLSearchParams({goal:o.goal,material:o.material,volume:o.volume});document.querySelector('#route-inquiry').href=prefix+'contact.html?'+params+'#inquiry';result.hidden=false;result.focus({preventScroll:true});result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});});}
const inquiry=document.querySelector('#inquiry-form');if(inquiry){const q=new URLSearchParams(location.search);const o={goal:q.get('goal'),material:q.get('material'),volume:q.get('volume')};if(valid(o)){inquiry.elements.part.value=goals[o.goal][en?1:0];inquiry.elements.material.value=materials[o.material][en?1:0];inquiry.elements.quantity.value=volumes[o.volume][en?1:0];inquiry.elements.details.value=t('درخواست با کمک راهنمای انتخاب مسیر سایت آماده شده است.','Inquiry prepared with the website project route finder.')}}
})();

