from pathlib import Path
import re,json,html,xml.etree.ElementTree as ET
R=Path(__file__).resolve().parents[1];B='https://zhopinbarb.ir'
articles=[{
'slug':'manufacturing-from-sample','fa':'ساخت قطعه از روی نمونه؛ الزامات بررسی و اجرای سفارش','en':'Manufacturing from a sample: requirements and project scope',
'dfa':'اطلاعات موردنیاز برای بازسازی قطعه، تشخیص ابعاد حساس و تعیین دامنهٔ ساخت از روی نمونه.','den':'A practical brief for reproducing an existing component, documenting interfaces and defining the manufacturing scope.',
'service':'design','project':'nailer-punch','source':('Autodesk — Reverse engineering','https://www.autodesk.com/solutions/reverse-engineering'),
'fa_sections':[
('هدف از بازسازی باید مشخص باشد','ساخت از روی نمونه زمانی مطرح می‌شود که قطعهٔ موجود در دسترس است، اما نقشهٔ کامل یا تأمین‌کنندهٔ اولیه در اختیار نیست. نخست باید مشخص شود هدف، جایگزینی قطعه، اصلاح طراحی یا تولید تعداد بیشتری از آن است. این اهداف لزوماً به یک دامنهٔ کاری یکسان منتهی نمی‌شوند.','در رویکرد مهندسی معکوس، شناخت عملکرد و مستندسازی جزء موجود، مبنای بازسازی قرار می‌گیرد. صرف شباهت ظاهری برای تعیین مشخصات یک قطعهٔ صنعتی کافی نیست.'),
('چه اطلاعاتی همراه نمونه ارائه شود؟','شرح کاربرد، محل نصب، تصاویر مجموعه و مشخصات دستگاه، به تفسیر درست شکل قطعه کمک می‌کند. ابعاد اتصال، سوراخ‌ها، نشیمن‌ها و سطوحی که با قطعات دیگر درگیر هستند باید در مدارک مشخص شوند. اگر نمونه آسیب‌دیده یا فرسوده است، وضعیت آن نیز اعلام شود.','جنس، عملیات حرارتی و پوشش سطحی را در صورت وجود مستندات ارائه کنید. در نبود اطلاعات قطعی، این موارد باید به‌عنوان موضوعات نیازمند بررسی ثبت شوند؛ رنگ یا ظاهر قطعه، به‌تنهایی مبنای اعلام گرید ماده نیست.'),
('دامنهٔ سفارش چگونه تعریف می‌شود؟','تعداد موردنیاز، مسئولیت تهیهٔ نقشه، نیاز به نمونهٔ اولیه و روش تأیید ابعاد باید پیش از آغاز ساخت روشن شود. پیشنهاد می‌شود هر تغییر نسبت به نمونه، جداگانه مشخص و نسخهٔ نهایی مدارک مبنای سفارش قرار گیرد.','برای مقایسهٔ پیشنهادهای ساخت، فهرست یکسانی از جنس، پرداخت، عملیات تکمیلی و اقلام قابل‌تحویل ارائه کنید. قیمت‌هایی که دامنهٔ متفاوت دارند، مقایسهٔ مستقیمی ایجاد نمی‌کنند.'),
('ارتباط با سوابق ساخت ژوپین بارب','سنبهٔ تفنگ میخ‌کوب معرفی‌شده در بخش نمونه‌کارها، بر اساس نمونهٔ موجود و با فولاد MO40 و اجرای سخت‌کاری ساخته شده است. این مشخصات به همان پروژه مربوط است و نباید بدون بررسی به قطعهٔ دیگری تعمیم داده شود.','برای درخواست مشابه، تصویر نمونه، مدل دستگاه، تعداد و ابعاد مهم را ارسال کنید. مشخصات نهایی ماده و معیار پذیرش، پس از بررسی سفارش تعیین خواهد شد.')],
'en_sections':[
('Define the purpose of reproduction','Sample-based manufacture is relevant when an existing component is available but complete drawings are not. Establish whether the requirement is a replacement, a design revision or a repeat production order. Each represents a different scope.','Reverse engineering documents an existing component and its function. Visual similarity alone does not define an industrial part.'),
('Provide the surrounding context','Include the application, installation position, assembly photographs and equipment identification. Identify mating surfaces, holes and connection features. Disclose damage or wear in the supplied sample.','Provide material, heat-treatment and finish records where available. Unknown specifications should remain open review items; appearance alone is not a material grade declaration.'),
('Establish an agreed manufacturing scope','Specify quantity, drawing responsibility, prototype requirements and dimensional acceptance arrangements. Document departures from the sample and identify the final revision used for the order.','Use the same material, finishing and deliverable requirements when comparing quotations. Offers covering different scopes are not directly comparable.'),
('Related manufacturing reference','The nailer punch in our portfolio was reproduced from a sample using hardened MO40 steel. These specifications describe that project; they are not a default specification for other parts.','For a similar inquiry, provide photographs, equipment identification, quantity and critical dimensions. Final specifications require project-specific review.')]
},{
'slug':'prototype-before-production','fa':'نمونه‌سازی پیش از تولید؛ تفکیک بررسی شکل، مونتاژ و عملکرد','en':'Prototyping before production: form, fit and function',
'dfa':'تعیین هدف نمونه‌سازی و ثبت نتایج بررسی پیش از تصمیم‌گیری دربارهٔ تولید قطعه.','den':'Define what a prototype must demonstrate and document the findings before production decisions.',
'service':'3d-printing','project':'printed-fan','source':('Protolabs — Selecting a rapid prototyping process','https://www.protolabs.com/resources/guides-and-trend-reports/rapid-prototyping-processes/'),
'fa_sections':[
('نمونه باید به یک پرسش مشخص پاسخ دهد','پیش از سفارش نمونه، موضوع بررسی را تعیین کنید: آیا هدف، مشاهدهٔ هندسه است، کنترل نصب در مجموعه یا ارزیابی عملکرد؟ این تفکیک در انتخاب روش و مشخصات نمونه اهمیت دارد.','در منابع تخصصی نمونه‌سازی نیز شکل، انطباق و عملکرد به‌عنوان اهداف متمایز مطرح می‌شوند. نمونه‌ای که صرفاً برای نمایش شکل ساخته شده، به‌خودی‌خود شواهدی دربارهٔ دوام یا عملکرد قطعهٔ نهایی ارائه نمی‌کند.'),
('پرسش‌های بررسی را مکتوب کنید','برای بررسی هندسه، ابعاد کلی و محدودیت فضای نصب را مشخص کنید. برای مونتاژ، قطعات مجاور و ترتیب نصب را معرفی کنید. در بررسی عملکرد، شرایط موردنظر و معیار ارزیابی باید پیش از ساخت نمونه توافق شوند.','ثبت یک فهرست کوتاه از پرسش‌ها، جلسهٔ بررسی نمونه را هدفمند می‌کند. نتیجهٔ هر مورد باید به‌صورت تأیید، اصلاح لازم یا نیازمند بررسی بیشتر ثبت شود.'),
('پرینت سه‌بعدی چه جایگاهی دارد؟','پرینت سه‌بعدی یکی از مسیرهای قابل‌بررسی برای نمونه‌سازی است؛ انتخاب آن باید با هدف نمونه و مادهٔ موردنیاز سازگار باشد. برای هر قطعه، مناسب‌بودن روش به‌صورت جداگانه ارزیابی می‌شود.','در نمونه‌کار هواکش موتور جرثقیل ژوپین بارب، قطعهٔ پرینتی برای نصب ساخته شده و مادهٔ اعلام‌شده پلی‌پروپیلن با ۳۰ درصد الیاف است. این سابقه، به‌معنای مناسب‌بودن همین ماده و روش برای تمام قطعات نیست.'),
('از نمونه به تولید','پیش از تولید، تغییرات پذیرفته‌شده در نقشه یا شرح فنی ثبت و نسخهٔ نهایی مشخص شود. تعداد سفارش، ماده، پرداخت و معیار پذیرش باید با این نسخه تطبیق داشته باشد.','برای استعلام نمونه‌سازی، کاربرد قطعه، هدف نمونه، مدارک موجود و زمان موردنظر را اعلام کنید. هزینه و زمان اجرا پس از بررسی این اطلاعات تعیین می‌شود.')],
'en_sections':[
('Assign a specific purpose to the prototype','Determine whether the prototype is intended to demonstrate geometry, verify assembly or evaluate function. The purpose informs the process and material requirements.','Prototyping guidance distinguishes form, fit and function. A visual model alone does not establish the durability or operating performance of a production part.'),
('Document the questions to be resolved','For geometry review, describe the overall dimensions and available installation space. For assembly review, identify adjacent components and installation sequence. Functional evaluation requires an agreed test purpose and acceptance criteria.','Record each finding as accepted, requiring revision or requiring further review. This creates a clear basis for the next design decision.'),
('Consider additive manufacturing in context','3D printing is one possible prototyping route. Its suitability must be assessed against the prototype purpose and material requirements.','The crane motor fan shown in our portfolio was printed as an installation component using polypropylene with 30% fibre reinforcement. That project does not establish the suitability of the same process or material for every application.'),
('Control the transition to production','Record approved revisions in the drawing or technical brief and identify the final version. Align the production quantity, material, finish and acceptance criteria with that version.','An inquiry should state the application, prototype purpose, available documents and requested date. Cost and schedule follow technical review.')]
},{
'slug':'industrial-rfq-checklist','fa':'راهنمای تهیهٔ درخواست قیمت برای ساخت قطعات صنعتی','en':'Preparing a manufacturing request for quotation',
'dfa':'چک‌لیست مشخصات فنی، تعداد، زمان و مقصد تحویل برای استعلام ساخت تکی و سری.','den':'A structured checklist covering specifications, quantity, schedule and delivery destination for manufacturing inquiries.',
'service':'metal','project':'couplings','source':None,
'fa_sections':[
('درخواست قیمت باید دامنهٔ مشخص داشته باشد','درخواست قیمت، شرح اولیهٔ موضوع سفارش است. عنوان قطعه به‌تنهایی معمولاً برای تعیین دامنهٔ ساخت کافی نیست. مشخص کنید چه محصولی، برای چه کاربردی و در چه تعدادی موردنیاز است.','این مقاله یک راهنمای تهیهٔ درخواست است. امکان اجرا، مبلغ و زمان تحویل هر سفارش پس از بررسی اطلاعات و توافق طرفین مشخص می‌شود.'),
('مشخصات فنی و مدارک','نقشه، مدل یا تصویر موجود را همراه با واحد اندازه‌گیری و شمارهٔ نسخه ارائه کنید. جنس پیشنهادی، ابعاد حساس، پرداخت و عملیات تکمیلی موردنیاز را مشخص کنید. اطلاعات نامعلوم را صریحاً با عنوان نیازمند بررسی درج کنید.','اگر گزارش اندازه‌گیری، گواهی ماده یا مدرک دیگری لازم است، آن را از ابتدا اعلام کنید. امکان ارائهٔ مدارک باید برای همان سفارش بررسی و تأیید شود.'),
('تعداد و تحویل','تعداد نمونه و تعداد تولید اصلی را جداگانه اعلام کنید. تاریخ موردنظر و مقصد تحویل نیز بخشی از درخواست هستند. برای همکاری بین‌المللی، کشور و شهر مقصد، نیاز بسته‌بندی و شرایط مدنظر تحویل را درج کنید.','اعلام مقصد به‌معنای تأیید حمل نیست؛ امکان اجرا و ترتیبات تحویل باید پیش از نهایی‌سازی سفارش بررسی شوند. چنانچه چند مرحلهٔ تحویل موردنیاز است، تعداد و تاریخ هر مرحله را مشخص کنید.'),
('بازبینی پیش از ارسال','کنترل کنید نام فایل‌ها و نسخهٔ مدارک با متن درخواست یکسان باشد. مشخصات تماس پاسخ‌گو، فهرست اقلام و پرسش‌های باز را درج کنید. برای مقایسهٔ پیشنهادها، دامنهٔ یکسانی در اختیار سازندگان قرار دهید.','در فرم سایت ژوپین بارب، متن اولیهٔ درخواست آماده می‌شود؛ سپس متقاضی می‌تواند آن را در برنامهٔ ایمیل باز کرده و فایل‌های فنی را پیوست کند. آماده‌شدن متن در سایت به‌معنای ارسال یا پذیرش سفارش نیست.')],
'en_sections':[
('Define the scope of the inquiry','A request for quotation describes the proposed order. A part name alone rarely establishes the complete scope. Identify the required component, application and quantity.','This article is a preparation guide. Feasibility, pricing and delivery dates are determined following review and agreement.'),
('Identify technical documents','Provide available drawings, models or photographs with measurement units and revision identifiers. State the proposed material, critical dimensions, finish and additional processing. Mark unresolved specifications as review items.','Declare any required inspection reports or material documentation at the outset. Availability must be confirmed for the particular order.'),
('Separate quantity and delivery requirements','Specify prototype and production quantities separately. Include the requested date and delivery location. International inquiries should identify the destination country and city, packaging requirements and proposed delivery arrangements.','Naming a destination does not confirm shipping availability. Feasibility and delivery arrangements require agreement before the order is finalized. Describe any staged deliveries separately.'),
('Review the package before submission','Ensure filenames and document revisions match the inquiry. Include a contact person, item list and unresolved questions. Use consistent requirements when comparing supplier responses.','The Zhopin Barb form prepares inquiry text for copying or opening in an email application. Technical files can then be attached to the email. Preparing the text does not send or accept an order.')]
}]
def page(path,title,desc,body,en,article=None):
 pre='/en/' if en else '/';base=R/('en/about.html' if en else 'about.html');s=base.read_text(encoding='utf8');canon=B+pre+path
 s=re.sub(r'<main id="main">.*?</main>','<main id="main">'+body+'</main>',s,flags=re.S);s=re.sub(r'<title>.*?</title>','<title>'+title+' | '+('Zhopin Barb' if en else 'ژوپین بارب')+'</title>',s)
 s=re.sub(r'<meta name="description"[^>]*>','<meta name="description" content="'+html.escape(desc,quote=True)+'">',s)
 s=re.sub(r'<link rel="canonical"[^>]*>','<link rel="canonical" href="'+canon+'">',s)
 s=re.sub(r'<link rel="alternate"[^>]*>','',s);s=re.sub(r'<meta property="og:(title|description|url|type)"[^>]*>','',s)
 s=re.sub(r'<script type="application/ld\+json">.*?</script>','',s,flags=re.S)
 schema={'@context':'https://schema.org','@type':'BlogPosting' if article else 'CollectionPage','headline':title,'description':desc,'url':canon,'inLanguage':'en' if en else 'fa','publisher':{'@type':'Organization','name':'Zhopin Barb','url':B,'logo':{'@type':'ImageObject','url':B+'/assets/brand/zhopinbarb-mark.png'}}}
 if article:schema.update({'datePublished':'2026-10-05','dateModified':'2026-10-05','author':{'@type':'Organization','name':'Zhopin Barb','url':B+'/about.html'},'mainEntityOfPage':canon})
 s=s.replace('</head>','<meta property="og:title" content="'+title+'"><meta property="og:description" content="'+desc+'"><meta property="og:type" content="'+('article' if article else 'website')+'"><meta property="og:url" content="'+canon+'"><script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script>'+''.join(f'<link rel="alternate" hreflang="{lang}" href="{B+pr+path}">' for lang,pr in [('fa','/'),('en','/en/'),('x-default','/')])+'</head>')
 s=s.replace(' aria-current="page"','');s=re.sub(r'(<a class="language-switch" href=")[^"]+',r'\g<1>'+('/' if en else '/en/')+path,s)
 dest=R/('en' if en else '')/path;dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(s,encoding='utf8')
for en in [False,True]:
 pre='/en/' if en else '/';key='en' if en else 'fa'
 def t(fa,eng):return eng if en else fa
 cards=''
 for a in articles:
  title=a[key];desc=a['d'+key];sections=a[key+'_sections'];toc=''.join(f'<a href="#section-{i}">{h}</a>' for i,(h,*_) in enumerate(sections,1))
  content=''.join(f'<section id="section-{i}"><h2>{h}</h2>'+''.join('<p>'+x+'</p>' for x in ps)+'</section>' for i,(h,*ps) in enumerate(sections,1))
  if a['source']:content+='<p class="article-source">'+t('مطالعهٔ تکمیلی: ','Further reading: ')+f'<a href="{a["source"][1]}">{a["source"][0]}</a></p>'
  content+='<div class="article-related"><h2>'+t('خدمات و سوابق مرتبط','Related capability and project')+'</h2><a href="'+pre+'services/'+a['service']+'.html">'+t('مشاهدهٔ خدمت مرتبط','View related capability')+'</a><a href="'+pre+'projects/'+a['project']+'.html">'+t('مشاهدهٔ نمونه‌کار مرتبط','View related project')+'</a></div><div class="article-banner"><p>'+t('برای بررسی سفارش، مشخصات قطعه و مدارک موجود را ارائه فرمایید.','Provide the part requirements and available documents for project review.')+'</p><a class="btn btn-primary" href="'+pre+'contact.html#inquiry">'+t('تهیهٔ درخواست فنی','Prepare a technical inquiry')+'</a></div>'
  body='<section class="page-head"><div class="container"><p class="eyebrow">'+t('مقالات تخصصی / ژوپین بارب','TECHNICAL ARTICLES / ZHOPIN BARB')+'</p><h1>'+title+'</h1><p class="lede">'+desc+'</p><p class="article-meta">'+t('ژوپین بارب | انتشار: ۱۳ مهر ۱۴۰۵','Zhopin Barb | Published: 5 October 2026')+'</p></div></section><div class="container section article-layout"><article class="article-body">'+content+'</article><aside class="article-toc" aria-label="'+t('فهرست مقاله','Article contents')+'"><strong>'+t('فهرست مطالب','Contents')+'</strong>'+toc+'</aside></div>'
  page('articles/'+a['slug']+'.html',title,desc,body,en,a)
  cards+='<article class="article-card"><p class="eyebrow">'+t('راهنمای تخصصی','TECHNICAL GUIDE')+'</p><h2>'+title+'</h2><p>'+desc+'</p><a class="inline-link dark" href="'+pre+'articles/'+a['slug']+'.html">'+t('مطالعهٔ مقاله','Read article')+' ↗</a></article>'
 title=t('مقالات تخصصی و راهنمای سفارش ساخت','Technical articles and manufacturing guides');desc=t('مطالب کاربردی دربارهٔ ساخت از روی نمونه، نمونه‌سازی و تدوین درخواست فنی.','Practical guidance on sample-based manufacturing, prototyping and technical inquiries.')
 page('articles.html',title,desc,'<section class="page-head"><div class="container"><p class="eyebrow">'+t('دانش فنی و راهنمای همکاری','TECHNICAL KNOWLEDGE')+'</p><h1>'+title+'</h1><p class="lede">'+desc+'</p></div></section><section class="container section article-grid">'+cards+'</section>',en)
for p in R.rglob('*.html'):
 s=p.read_text(encoding='utf8');en=p.relative_to(R).parts[0]=='en';pre='/en/' if en else '/'
 if 'class="articles-nav"' not in s:s=s.replace('<a class="language-switch"','<a class="articles-nav" href="'+pre+'articles.html">'+('Articles' if en else 'مقالات')+'</a><a class="language-switch"',1)
 p.write_text(s,encoding='utf8')
ET.register_namespace('','http://www.sitemaps.org/schemas/sitemap/0.9');tree=ET.Element('{http://www.sitemaps.org/schemas/sitemap/0.9}urlset')
for p in sorted(R.rglob('*.html')):
 rel=p.relative_to(R).as_posix()
 if rel=='404.html':continue
 ET.SubElement(ET.SubElement(tree,'url'),'loc').text=B+'/'+(rel[:-10] if rel.endswith('index.html') else rel)
ET.ElementTree(tree).write(R/'sitemap.xml',encoding='utf-8',xml_declaration=True)
print('3 bilingual articles, 2 index pages, 48 sitemap URLs')
