from pathlib import Path
R=Path(__file__).resolve().parents[1]
for en in [False,True]:
 p=R/('en/contact.html' if en else 'contact.html');s=p.read_text(encoding='utf8')
 if 'id="inquiry"' in s:continue
 def t(fa,eng):return eng if en else fa
 fields=[('name',t('نام و شرکت','Name / company'),'text',True),('reply',t('ایمیل یا شماره تماس','Email or phone'),'text',True),('part',t('نام قطعه یا پروژه','Part / project'),'text',True),('quantity',t('تعداد موردنیاز','Required quantity'),'text',False),('material',t('جنس یا مشخصات ماده','Material specification'),'text',False),('destination',t('شهر / کشور تحویل','Delivery city / country'),'text',False)]
 form='<section id="inquiry" class="section inquiry-section"><div class="container inquiry-layout"><div><p class="eyebrow">'+t('شروع بررسی فنی','PROJECT INQUIRY')+'</p><h2>'+t('درخواست دقیق‌تر، بررسی بهتر.','A clearer brief. A better starting point.')+'</h2><p class="body-copy">'+t('اطلاعات اولیهٔ پروژه را وارد کنید تا متن درخواست شما آماده شود. اگر جنس یا تعداد هنوز مشخص نیست، همان را توضیح دهید.','Prepare your initial brief. If the material or quantity is not yet defined, simply explain what you know.')+'</p><p class="inquiry-note">'+t('این فرم اطلاعات را روی سرور ذخیره یا ارسال نمی‌کند. در مرحلهٔ بعد متن را کپی کنید یا در برنامهٔ ایمیل باز کنید؛ عکس و نقشه را به ایمیل پیوست کنید.','This form does not store or send your information to a server. Copy the prepared brief or open it in your email app, then attach your drawings or photographs.')+'</p></div><form id="inquiry-form"><div class="inquiry-fields">'
 for key,label,typ,required in fields:
  form+=f'<label for="inquiry-{key}">{label}'+(' *' if required else '')+f'<input id="inquiry-{key}" name="{key}" type="{typ}" maxlength="180" '+('required ' if required else '')+('autocomplete="name"' if key=='name' else '')+'></label>'
 form+='</div><label for="inquiry-details">'+t('کاربرد، ابعاد مهم و زمان موردنظر','Application, critical dimensions and target date')+'<textarea id="inquiry-details" name="details" rows="5" maxlength="2500"></textarea></label><button class="btn btn-primary" type="submit">'+t('آماده‌سازی متن درخواست','Prepare inquiry')+'</button><noscript><p>'+t('برای آماده‌سازی خودکار متن، جاوااسکریپت را فعال کنید یا مستقیماً ایمیل بفرستید.','Enable JavaScript to prepare a brief, or email us directly.')+'</p></noscript><div id="inquiry-result" hidden><h3>'+t('متن آماده است؛ هنوز ارسال نشده.','Your brief is ready. It has not been sent.')+'</h3><label for="inquiry-preview">'+t('متن درخواست','Inquiry text')+'<textarea id="inquiry-preview" readonly rows="10"></textarea></label><div class="inquiry-actions"><a id="inquiry-email" class="btn btn-primary">'+t('باز کردن در ایمیل','Open in email app')+'</a><button id="inquiry-copy" class="btn" type="button">'+t('کپی متن','Copy brief')+'</button></div><p id="inquiry-status" role="status"></p></div></form></div></section>'
 s=s.replace('</main>',form+'</main>');p.write_text(s,encoding='utf8')
