from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
for en in [False,True]:
 p=R/('en/about.html' if en else 'about.html');s=p.read_text(encoding='utf8')
 def t(fa,eng):return eng if en else fa
 items=[('review','22 May 2023','۲۲ مهٔ ۲۰۲۳',t('نشست بررسی و ساخت تجهیزات وودبال','Woodball equipment development meeting'),t('نشست با حضور مسئولان انجمن وودبال و نمایندگان شرکت پیشین؛ در توضیح پست، نام «آویژه صنعت نگین بعثت» درج شده است.','A meeting involving the woodball association and the former company. The post identifies Avijeh Sanat Negin Besat.'),'https://www.instagram.com/p/CsjBpF2ARkS/'),('equipment','12 July 2023','۱۲ ژوئیهٔ ۲۰۲۳',t('معرفی تجهیزات تولید داخل','Presentation of domestically produced equipment'),t('تصویر تجهیزات وودبال در اطلاع‌رسانی انجمن دربارهٔ برنامهٔ رونمایی از تولید داخل.','Woodball equipment pictured in the association’s announcement of the domestic-production unveiling.'),None),('unveiling','16 July 2023','۱۶ ژوئیهٔ ۲۰۲۳',t('گزارش تصویری مراسم رونمایی','Photographic report of the unveiling'),t('گزارش منتشرشده از رونمایی ادوات تولید داخل، با حضور مسئولان فدراسیون و انجمن وودبال.','A published account of the domestic equipment unveiling, attended by federation and woodball association representatives.'),'https://www.instagram.com/p/CuwPJLPu_dc/')]
 figures=''
 for key,date,fa_date,title,desc,link in items:
  figures+=f'<figure class="history-card"><div class="history-photo history-{key}"><img src="/assets/history/woodball-{key}-2023.jpg" alt="{title}" width="591" height="1280" loading="lazy"></div><figcaption><span class="eyebrow">{t("انتشار گزارش: ","POST PUBLISHED: ")+(date if en else fa_date)}</span><h3>{title}</h3><p>{desc}</p>'+(f'<a href="{link}" target="_blank" rel="noopener noreferrer">'+t('مشاهده پست منبع','View source post')+' ↗</a>' if link else '')+'</figcaption></figure>'
 section='<section id="company-history" class="section history-section"><div class="container"><div class="history-intro"><div><p class="eyebrow">'+t('پیشینهٔ فنی و سوابق فعالیت','TECHNICAL BACKGROUND & COMPANY HISTORY')+'</p><h2>'+t('توسعهٔ تجهیزات وودبال؛<br>بخشی از پیشینهٔ ساخت مجموعه','Woodball equipment development.<br>Part of our manufacturing background.')+'</h2></div><div><p>'+t('بخشی از پیشینهٔ فنی مجموعه به فعالیت در شرکت فنی‌مهندسی «آویژه صنعت نگین بعثت» بازمی‌گردد. تصاویر زیر، نشست بررسی تجهیزات وودبال و گزارش‌های معرفی و رونمایی از تولید داخل در سال ۱۴۰۲ را مستند می‌کنند.','Part of the team’s technical background relates to its earlier work at Avijeh Sanat Negin Besat, the former engineering company. These images document the equipment review meeting and the domestic-production presentation and unveiling reports published in 2023.')+'</p><p>'+t('این مطالب با حفظ نام شرکت پیشین و ارجاع به گزارش‌های صفحهٔ انجمن وودبال ایران ارائه شده‌اند.','The historical material retains the former company’s name and references the posts published by the Iran Woodball Association account.')+'</p></div></div><div class="history-grid">'+figures+'</div><p class="history-source">'+t('منبع تصاویر و توضیحات رویدادها: صفحهٔ iran_woodball_association؛ تصاویر ارسالی مجموعه.','Event photographs and descriptions: iran_woodball_association, from screenshots supplied by the company.')+'</p></div></section>'
 s=re.sub(r'<section id="company-history".*?</section>','',s,flags=re.S)
 s=s.replace('</main>',section+'</main>')
 if '/history.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/history.css?v=20261005"></head>')
 p.write_text(s,encoding='utf8')
print('Historical section added in both languages')
