from pathlib import Path
import re,json,html,xml.etree.ElementTree as ET
R=Path(__file__).resolve().parents[1];B='https://zhopinbarb.ir'
for en in [False,True]:
 prefix='/en/' if en else '/';p=R/('en/international.html' if en else 'international.html')
 def t(fa,eng):return eng if en else fa
 title=t('همکاری با خریداران بین‌المللی','For international buyers')
 desc=t('بررسی سفارش ساخت قطعات صنعتی با مشخصات فنی، تعداد و مقصد تحویل؛ از نمونه و نقشه تا پیشنهاد روش تولید.','Discuss custom industrial components with a clear technical brief, order quantity and delivery destination.')
 steps=[(t('تعریف نیاز','Define the requirement'),t('کاربرد، نمونه یا نقشه، جنس، تعداد و مقصد تحویل را اعلام کنید.','Share the application, sample or drawing, material, quantity and delivery destination.')),(t('بررسی فنی','Review the manufacturing route'),t('ابعاد حساس، روش تولید و نیاز به نمونه‌سازی پیش از پیشنهاد قیمت بررسی می‌شوند.','Critical dimensions, process options and any prototyping needs are reviewed before quotation.')),(t('توافق بر دامنه سفارش','Agree the order scope'),t('مشخصات نهایی، معیار پذیرش، زمان‌بندی، بسته‌بندی و شرایط تحویل باید برای هر سفارش توافق شوند.','Final specifications, acceptance criteria, schedule, packaging and delivery terms are agreed for each order.')),(t('ساخت بر اساس مشخصات','Manufacture to the agreed brief'),t('ساخت تکی یا سری بر اساس دامنه و مشخصات توافق‌شده انجام می‌شود.','One-off or batch manufacture follows the agreed scope and specifications.'))]
 checks=[t('نقشه یا تصویر با مشخص‌بودن واحد اندازه‌گیری','Drawing or photographs with measurement units'),t('جنس، گرید و شرایط کار قطعه','Material grade and operating conditions'),t('تعداد نمونه و تعداد سفارش اصلی','Prototype quantity and production quantity'),t('ابعاد حساس و معیار پذیرش','Critical dimensions and acceptance criteria'),t('کشور، شهر و زمان موردنظر برای تحویل','Delivery country, city and requested date'),t('نیازهای بسته‌بندی و مستندات موردنیاز','Packaging and documentation requirements')]
 faqs=[(t('آیا سفارش تکی قابل بررسی است؟','Can I inquire about a single part?'),t('بله؛ سفارش تکی و سری بررسی می‌شود. روش مناسب ساخت پس از بررسی قطعه مشخص خواهد شد.','Yes. Both one-off and batch requirements can be reviewed. The suitable production route depends on the part.')),(t('اگر نقشه کامل نداشته باشم چه می‌شود؟','What if I do not have a complete drawing?'),t('عکس، نمونه یا شرح کاربرد می‌تواند مبنای شروع گفت‌وگو باشد. جزئیات لازم پیش از تولید تکمیل می‌شوند.','A photograph, sample or application brief can start the conversation. Required details are resolved before production.')),(t('شرایط حمل و تحویل چگونه مشخص می‌شود؟','How are delivery arrangements confirmed?'),t('امکان اجرای سفارش و شرایط حمل، بسته‌بندی و تحویل برای مقصد موردنظر، پیش از نهایی‌شدن سفارش بررسی و توافق می‌شوند.','Order feasibility, packaging, shipping and delivery arrangements for your destination are reviewed and agreed before an order is finalized.')),(t('آیا برای همه قطعات گواهی یا گزارش آزمون وجود دارد؟','Are certificates or test reports available for every part?'),t('مدارک موردنیاز را در درخواست ذکر کنید. امکان ارائه هر مدرک باید برای همان سفارش بررسی و تأیید شود.','Specify required documents in your inquiry. Availability of each certificate or report must be reviewed and confirmed for that order.'))]
 body=f'<section class="page-head"><div class="container"><p class="eyebrow">{t("ژوپین بارب / همکاری بین‌المللی","ZHOPIN BARB / INTERNATIONAL INQUIRIES")}</p><h1>{t("از نیاز فنی شما،<br>تا مسیر روشن ساخت.","Your requirements.<br>A clear manufacturing brief.")}</h1><p class="lede">{desc}</p><a class="btn btn-primary space-top" href="{prefix}contact.html#inquiry">{t("آماده‌سازی درخواست قیمت","Prepare a quotation inquiry")} ↗</a></div></section>'
 body+='<section class="section container detail-layout"><div><p class="eyebrow">'+t('دامنه توانمندی‌ها','MANUFACTURING SCOPE')+'</p><h2>'+t('قطعات سفارشی برای کاربرد شما.','Custom parts for your application.')+'</h2><p class="body-copy">'+t('طراحی و ساخت قطعات فلزی، پلیمری و کامپوزیتی، نمونه‌سازی با پرینت سه‌بعدی و تجهیزات ورزشی. نمونه‌کارهای سایت، جنس و دامنه اجرای پروژه‌های معرفی‌شده را نشان می‌دهند.','Design and manufacturing of metal, polymer and composite components, 3D-printed prototypes and sports equipment. Our project pages describe the materials and scope of documented work.')+'</p><a class="inline-link dark" href="'+prefix+'projects.html">'+t('بررسی نمونه‌کارها','Review our project portfolio')+' ↗</a></div><aside class="spec-panel"><h2>'+t('برای بررسی سفارش آماده کنید','What to include in your inquiry')+'</h2><ul>'+''.join('<li>'+c+'</li>' for c in checks)+'</ul></aside></section>'
 body+='<section class="approach section"><div class="container approach-grid"><div><p class="eyebrow">'+t('مسیر همکاری','HOW WE WORK')+'</p><h2>'+t('جزئیات پیش از تولید<br>مشخص می‌شوند.','Define the details.<br>Then move to production.')+'</h2></div><ol class="timeline">'+''.join(f'<li><span class="step">0{i+1}</span><div><h3>{a}</h3><p>{b}</p></div></li>' for i,(a,b) in enumerate(steps))+'</ol></div></section>'
 body+='<section class="section container buyer-faq"><p class="eyebrow">'+t('پرسش‌های خریداران','BUYER QUESTIONS')+'</p><h2 class="space-bottom">'+t('پیش از شروع همکاری','Before you get started')+'</h2>'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in faqs)+'</section>'
 s=(R/('en/about.html' if en else 'about.html')).read_text(encoding='utf8');s=re.sub(r'<main id="main">.*?</main>','<main id="main">'+body+'</main>',s,flags=re.S)
 s=re.sub(r'<title>.*?</title>','<title>'+title+' | '+('Zhopin Barb' if en else 'ژوپین بارب')+'</title>',s)
 s=re.sub(r'<meta name="description"[^>]*>','<meta name="description" content="'+html.escape(desc,quote=True)+'">',s)
 s=re.sub(r'<meta property="og:(title|description|url)"[^>]*>','',s)
 s=re.sub(r'<link rel="canonical"[^>]*>','<link rel="canonical" href="'+B+prefix+'international.html">',s)
 s=re.sub(r'<link rel="alternate"[^>]*>','',s)
 s=re.sub(r'<script type="application/ld\+json">.*?</script>','',s,flags=re.S)
 graph={'@context':'https://schema.org','@type':'WebPage','name':title,'url':B+prefix+'international.html','inLanguage':'en' if en else 'fa','about':{'@id':B+'/#organization'}}
 s=s.replace('</head>','<meta property="og:title" content="'+title+'"><meta property="og:description" content="'+desc+'"><meta property="og:url" content="'+B+prefix+'international.html"><script type="application/ld+json">'+json.dumps(graph,ensure_ascii=False)+'</script></head>')
 s=s.replace(' aria-current="page"','');s=re.sub(r'(<a class="language-switch" href=")[^"]+',r'\g<1>'+('/international.html' if en else '/en/international.html'),s)
 p.write_text(s,encoding='utf8')
# Upgrade navigation and add reciprocal alternates to new pages.
for p in R.rglob('*.html'):
 if p.name=='404.html':continue
 s=p.read_text(encoding='utf8');en='en'==p.relative_to(R).parts[0];prefix='/en/' if en else '/'
 if 'class="international-nav"' not in s:s=s.replace('<a class="language-switch"',f'<a class="international-nav" href="{prefix}international.html"'+(' aria-current="page"' if p.name=='international.html' else '')+'>'+('International' if en else 'همکاری بین‌المللی')+'</a><a class="language-switch"',1)
 if p.name=='international.html':s=s.replace('</head>',f'<link rel="alternate" hreflang="fa" href="{B}/international.html"><link rel="alternate" hreflang="en" href="{B}/en/international.html"><link rel="alternate" hreflang="x-default" href="{B}/international.html"></head>')
 if p.name=='index.html' and 'id="international-intro"' not in s:
  block='<section id="international-intro" class="section container international-intro"><div><p class="eyebrow">'+('FOR INTERNATIONAL BUYERS' if en else 'همکاری با خریداران خارجی')+'</p><h2>'+('A technical conversation,<br>before a commercial commitment.' if en else 'بررسی فنی روشن،<br>پیش از توافق تجاری.')+'</h2><p class="body-copy">'+('Explore documented projects, share your specifications and tell us your delivery destination. Order feasibility and delivery arrangements are confirmed individually.' if en else 'نمونه‌کارها را بررسی کنید و مشخصات قطعه، تعداد و مقصد تحویل را بفرستید. امکان اجرای سفارش و شرایط تحویل، برای هر پروژه جداگانه مشخص می‌شود.')+'</p></div><a class="btn btn-primary" href="'+prefix+'international.html">'+('International buyer guide ↗' if en else 'راهنمای همکاری بین‌المللی ↙')+'</a></section>'
  s=s.replace('<section class="section container">',block+'<section class="section container">',1)
 s=s.replace('/professional.css?v=20261004','/professional.css?v=20261005').replace('/professional.js?v=20261004','/professional.js?v=20261005')
 p.write_text(s,encoding='utf8')
ET.register_namespace('','http://www.sitemaps.org/schemas/sitemap/0.9');tree=ET.Element('{http://www.sitemaps.org/schemas/sitemap/0.9}urlset')
for p in sorted(R.rglob('*.html')):
 rel=p.relative_to(R).as_posix()
 if rel=='404.html':continue
 ET.SubElement(ET.SubElement(tree,'url'),'loc').text=B+'/'+(rel[:-10] if rel.endswith('index.html') else rel)
ET.ElementTree(tree).write(R/'sitemap.xml',encoding='utf-8',xml_declaration=True)
print('International buyer journey added; 40 indexable pages')
