from pathlib import Path
import html,json,re,xml.etree.ElementTree as ET
R=Path(__file__).resolve().parents[1]; B='https://zhopinbarb.ir'; E=html.escape
P=[
('cable-reel','Crane cable reel','industrial','Port equipment',['cable-reel'],'Fabrication of an iron cable reel for a crane application at a southern Iranian port.',[('Diameter','2.4 m'),('Material','Iron'),('Scope','Reel fabrication; complete assembly available subject to project review')],'The documented reel demonstrates large circular fabrication. Cable specification, drive arrangement and installation interfaces are agreed individually for a complete assembly.'),
('printed-fan','3D-printed crane motor fan','industrial','Polymer components',['printed-fan'],'A functional motor ventilation component made by 3D printing for installation.',[('Material','Polypropylene with 30% fibre reinforcement'),('Process','3D printing'),('Purpose','Installation component')],'The application uses additive manufacturing for a final component. Fibre type, operating conditions and dimensional requirements are confirmed during technical review.'),
('composite-fan','Composite cooling fan','industrial','Heavy motor cooling',['composite-fan'],'Design and manufacture of a fibreglass cooling fan for a heavy motor.',[('Diameter','1.5 m'),('Material','Fibreglass composite'),('Scope','Design and manufacture'),('Installation','Successfully installed, as reported by the company')],'The project included both design and fabrication. Operating speed, attachment geometry and acceptance criteria are reviewed for each new order.'),
('couplings','Power transmission couplings','industrial','Mechanical components',['coupling'],'Custom coupling components made in different steel grades and configurations.',[('Materials','Case-hardening steels and CK steel grades'),('Application','Power transmission'),('Orders','One-off and batch production')],'The appropriate steel grade and manufacturing route depend on the equipment, connection geometry and service conditions. The illustrated component is one example of the portfolio.'),
('woodball','Golf and woodball equipment','sports','Sports equipment',['woodball-gate','woodball-mallet'],'Manufacture and finishing of golf and woodball equipment and components.',[('Wooden balls','Beech wood'),('Woodball components','Including aluminium parts'),('Scope','Equipment, components and finishing')],'The portfolio includes woodball gates and mallets. Materials and construction are specified per component; the material of one item does not apply to the full assembly.'),
('cast-putters','Cast putter heads','sports','Casting and finishing',['cast-putter'],'Putter head production by casting, followed by finishing.',[('Material','Lead, as specified for this project'),('Process','Casting and finishing'),('Orders','Single and double-sided configurations')],'The image shows cast heads before final finishing. Shape, mass, attachment interface and finish are agreed before a new production run.'),
('portable-mini-golf','Folding portable mini-golf course','sports','In-house product design',['mini-golf'],'An in-house mini-golf design developed for portability and compact storage.',[('Design','Developed by our team'),('Transport','Portable and foldable'),('Folded volume','One quarter of the unfolded volume'),('Options','Custom layouts and dimensions')],'The design combines a playing surface, perimeter and target hole with a folding structure. Installation surface, available space and the required playing route inform each custom version.'),
('nailer-punch','Hardened nailer punch','industrial','Tool components',['nailer-punch'],'Manufacture of a replacement nailer punch from an existing sample.',[('Material','MO40 steel'),('Treatment','Hardened'),('Reference','Existing sample')],'Sample geometry and connection features guide reproduction. Equipment model, critical dimensions and required hardness are confirmed individually.')]
S=[('design','Design & sample-based development','Turn an idea, drawing or physical sample into a manufacturing brief.',['Application and interface review','Geometry and material selection','Prototyping where required'],['portable-mini-golf','nailer-punch']),('metal','Metal component manufacturing','Custom metal parts and assemblies, produced singly or in batches.',['Material selection','Sample-based fabrication','Finishing and heat treatment as agreed'],['cable-reel','couplings','nailer-punch']),('polymer','Polymer components','Select a polymer and production route around the intended application.',['Service conditions','Material and geometry review','One-off and batch requirements'],['printed-fan']),('3d-printing','3D printing & prototyping','Evaluate geometry and fit before production, or discuss a printed end-use component.',['Prototype geometry','Fit and assembly review','Material and process suitability'],['printed-fan']),('composite','Composite fabrication','Custom fibreglass components, including the documented heavy motor cooling fan.',['Geometry and installation interfaces','Material requirements','Project-specific fabrication'],['composite-fan']),('sports','Golf & woodball equipment','Custom sports equipment, from components to a folding mini-golf course.',['Golf and woodball components','Casting and finishing','Portable playing surfaces'],['woodball','cast-putters','portable-mini-golf'])]
def url(path):return '/en/'+('' if path=='index.html' else path)
def card(p):
 slug,t,g,cat,imgs,desc,facts,analysis=p
 return f'<article class="project-card" data-category="{g}"><a href="/en/projects/{slug}.html"><div class="project-thumb"><img src="/assets/projects/{imgs[0]}-studio.webp" width="600" height="600" loading="lazy" alt="{E(t)}"></div><div class="card-copy"><span class="eyebrow">{cat}</span><h3>{t}</h3><p>{desc}</p><span class="card-link">Explore project ↗</span></div></a></article>'
def cards(items):return '<div class="project-grid">'+''.join(map(card,items))+'</div>'
def head(t,d):return f'<section class="page-head"><div class="container"><p class="eyebrow">ZHOPIN BARB / ENGINEERING & MANUFACTURING</p><h1>{t}</h1><p class="lede">{d}</p></div></section>'
def cta():return '<section class="contact section"><div class="container"><p class="eyebrow">START A TECHNICAL CONVERSATION</p><h2>Tell us what you need to make.</h2><p>Send a drawing, photograph or description. Material, quantity, delivery requirements and the production route are reviewed before quotation.</p><a class="btn btn-primary" href="/en/contact.html#inquiry">Prepare your inquiry ↗</a></div></section>'
def services():return '<div class="cap-grid">'+''.join(f'<a class="cap-card" href="/en/services/{s[0]}.html"><span class="eyebrow">0{i+1} / CAPABILITY</span><h3>{s[1]}</h3><p>{s[2]}</p><span class="card-link">View capability ↗</span></a>' for i,s in enumerate(S))+'</div>'
def shell(path,title,desc,body,active):
 nav=''.join(f'<a href="{url(p)}"'+(' aria-current="page"' if p==active else '')+f'>{n}</a>' for p,n in [('index.html','Home'),('services.html','Capabilities'),('projects.html','Projects'),('about.html','About'),('contact.html','Contact')])
 fa='/'+('' if path=='index.html' else path);canon=B+url(path)
 graph={'@context':'https://schema.org','@type':'WebPage','name':title+' | Zhopin Barb','url':canon,'inLanguage':'en','isPartOf':{'@id':B+'/#website'},'about':{'@id':B+'/#organization'}}
 out=f'''<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | Zhopin Barb</title><meta name="description" content="{E(desc)}"><link rel="canonical" href="{canon}"><link rel="stylesheet" href="/style.css?v=20261004"><link rel="stylesheet" href="/professional.css?v=20261004"><link rel="icon" href="/assets/brand/favicon.png"><meta property="og:title" content="{E(title)} | Zhopin Barb"><meta property="og:description" content="{E(desc)}"><meta property="og:url" content="{canon}"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:image" content="{B}/assets/projects/cable-reel-studio.webp"><script type="application/ld+json">{json.dumps(graph)}</script></head><body><a class="skip" href="#main">Skip to content</a><div class="utility"><div class="container utility-inner"><span>ZHOPIN BARB / ASOO HAMRAH HOOSHMAND</span><details class="quick-contact"><summary>Contact us</summary><div class="quick-contact-panel"><a href="tel:+989122164836">+98 912 216 4836</a></div></details></div></div><header class="site-header"><div class="container nav-row"><a class="brand" href="/en/" aria-label="Zhopin Barb home"><img class="brand-logo" src="/assets/brand/zhopinbarb-mark.png" width="64" height="64" alt=""><span><strong>ZHOPIN BARB</strong><small>DESIGN · PROTOTYPE · MANUFACTURE</small></span></a><button class="menu" type="button" aria-controls="navigation" aria-expanded="false" aria-label="Open menu"><span></span><span></span><span></span></button><nav id="navigation" aria-label="Main navigation">{nav}</nav></div></header><main id="main">{body}</main><footer class="footer"><div class="container footer-main"><div class="footer-identity"><img class="brand-logo" src="/assets/brand/zhopinbarb-mark.png" width="64" height="64" alt=""><strong>ZHOPIN BARB</strong><span>A brand of Asoo Hamrah Hooshmand</span></div><div class="footer-links">{nav}</div></div><div class="container footer-bottom"><span>© Zhopin Barb</span><a href="mailto:zhopinbarb@gmail.com">zhopinbarb@gmail.com</a><a href="tel:+989122164836">+98 912 216 4836</a></div></footer><script src="/script.js?v=20261004"></script><script src="/professional.js?v=20261004" defer></script></body></html>'''
 dest=R/'en'/path;dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(out,encoding='utf8')
shell('index.html','Custom industrial parts, from concept to manufacture','Metal, polymer and composite components, 3D printing and sports equipment. Explore real projects and discuss one-off or batch manufacturing.', '<section class="hero"><div class="hero-photo"><img src="/assets/projects/cable-reel-studio.webp" width="1254" height="1254" alt="Fabricated port crane cable reel" fetchpriority="high"></div><div class="container hero-inner"><div class="hero-copy"><p class="overline light">CUSTOM COMPONENTS / REAL APPLICATIONS</p><h1>From your sample<br>to a <em>finished part.</em></h1><p>Design, prototyping and custom manufacturing in metal, polymer and composite materials. A practical production route, built around your application.</p><div class="hero-actions"><a class="btn btn-primary" href="/en/projects.html">Explore our work ↗</a><a class="btn btn-outline" href="/en/contact.html#inquiry">Discuss a project ↗</a></div></div></div></section><div class="scope-bar"><div class="container scope-inner"><span>One-off & batch orders</span><span>Sample-based development</span><span>Design & prototyping</span><span>Custom manufacturing</span></div></div><section class="section container"><p class="eyebrow">OUR CAPABILITIES</p><h2 class="space-bottom">The right process for the part.</h2>'+services()+'</section><section class="section projects-section"><div class="container"><h2 class="space-bottom">Selected projects</h2>'+cards([P[0],P[2],P[6]])+'</div></section>'+cta(),'index.html')
shell('services.html','Manufacturing capabilities','Design, metalworking, polymer components, composites, 3D printing and sports equipment.',head('Capabilities shaped around your project.','Material, geometry, quantity and intended use guide the manufacturing route.')+'<section class="section container">'+services()+'</section>'+cta(),'services.html')
for slug,title,desc,checks,related in S:
 shell('services/'+slug+'.html',title,desc,head(title,desc)+'<section class="section container detail-layout"><div><h2>Start with the application.</h2><p class="body-copy">We review the available sample, drawings or brief with your required quantity and service conditions. The scope, material and delivery requirements are agreed for each project.</p></div><aside class="spec-panel"><h2>Technical review</h2><ul>'+''.join('<li>'+c+'</li>' for c in checks)+'</ul></aside></section><section class="section projects-section"><div class="container"><h2 class="space-bottom">Related work</h2>'+cards([p for p in P if p[0] in related])+'</div></section>'+cta(),'services.html')
shell('projects.html','Project portfolio','Explore manufactured industrial components and sports equipment with materials, processes and project details.',head('Real parts. Different manufacturing routes.','A selection of industrial and sports projects, with materials and project-specific scope.')+'<section class="section container"><div class="filters" aria-label="Project categories"><button type="button" data-filter="all" aria-pressed="true">All projects</button><button type="button" data-filter="industrial" aria-pressed="false">Industrial parts</button><button type="button" data-filter="sports" aria-pressed="false">Sports equipment</button></div>'+cards(P)+'</section>'+cta(),'projects.html')
for slug,title,g,cat,imgs,desc,facts,analysis in P:
 gallery=''.join(f'<figure><a href="/assets/projects/{im}-studio.webp" aria-label="Enlarge {E(title)}"><img src="/assets/projects/{im}-studio.webp" alt="{E(title)}" width="1254" height="1254" loading="lazy"></a></figure>' for im in imgs)
 shell('projects/'+slug+'.html',title,desc,head(title,desc)+f'<section class="section container detail-layout"><div class="project-gallery">{gallery}</div><aside><div class="spec-panel"><h2>Project specifications</h2><dl>'+''.join(f'<div><dt>{k}</dt><dd>{v}</dd></div>' for k,v in facts)+'</dl></div><div class="analysis"><h2>Manufacturing context</h2><p>'+analysis+'</p></div><a class="btn btn-primary" href="/en/contact.html?project='+slug+'#inquiry">Discuss a similar part ↗</a></aside></section>'+cta(),'projects.html')
shell('about.html','About our company','Zhopin Barb is a brand of Asoo Hamrah Hooshmand, working in custom industrial parts and sports equipment.',head('Design decisions. Practical manufacturing.','Zhopin Barb is a brand of Asoo Hamrah Hooshmand, developing custom metal, polymer and composite components and sports equipment.')+'<section class="section container detail-layout"><div><h2>From a sample or an original design.</h2><p class="body-copy">Most documented projects were developed from existing samples. Our folding mini-golf course is an in-house design; the composite cooling fan also included design and fabrication. We review one-off and batch requirements with the aim of achieving the required quality at a suitable cost.</p></div><aside class="spec-panel"><h2>Company details</h2><dl><div><dt>Legal company</dt><dd>Asoo Hamrah Hooshmand</dd></div><div><dt>National ID</dt><dd>14011023806</dd></div><div><dt>Registration number</dt><dd>594293</dd></div></dl></aside></section>'+cta(),'about.html')
shell('contact.html','Contact & project inquiries','Discuss your drawings, sample, material, quantity and delivery requirements with Zhopin Barb.',head('Let’s define your next project.','An idea, photograph, drawing or existing component is enough to start the conversation.')+'<section class="section container detail-layout"><div><p class="eyebrow">DIRECT CONTACT</p><a class="phone" href="tel:+989122164836">+98 912 216 4836</a><p><a href="mailto:zhopinbarb@gmail.com">zhopinbarb@gmail.com</a></p><h2 class="space-top">Office</h2><address>Unit 2, Floor 1, No. 7, Ashehri dead end, Hafez Street, before Jomhouri Street, Tehran, Iran.</address><p>Postal code: 1134845412</p><h2 class="space-top">Workshop</h2><address>No. 1010, Alley 14, Sanat Street, Samen Al-Hojaj Trade and Services Complex.</address><p>Postal code: 1846192330</p><p>Please arrange a visit by phone in advance.</p></div><aside class="spec-panel"><h2>For your inquiry</h2><ul><li>Part application and operating conditions</li><li>Drawing, photograph or available sample</li><li>Material and quantity</li><li>Critical dimensions and delivery destination</li></ul><p>Pricing, schedule and delivery arrangements are confirmed after review.</p></aside></section>','contact.html')
# Reciprocal language links; keep existing Persian content intact.
for p in list(R.rglob('*.html')):
 rel=p.relative_to(R).as_posix()
 if rel=='404.html':continue
 en=rel.startswith('en/');base=rel[3:] if en else rel
 fa='/'+('' if base=='index.html' else base);eng=url(base)
 s=p.read_text(encoding='utf8')
 s=re.sub(r'<link rel="alternate" hreflang="[^"]+"[^>]*>','',s)
 s=s.replace('</head>',f'<link rel="alternate" hreflang="fa" href="{B+fa}"><link rel="alternate" hreflang="en" href="{B+eng}"><link rel="alternate" hreflang="x-default" href="{B+fa}"></head>')
 if 'class="language-switch"' not in s:s=s.replace('</nav>',f'<a class="language-switch" href="{fa if en else eng}" lang="{"fa" if en else "en"}" hreflang="{"fa" if en else "en"}">{"فارسی" if en else "English"}</a></nav>',1)
 if not en:
  s=s.replace('</head>','<link rel="stylesheet" href="/professional.css?v=20261004"></head>') if '/professional.css' not in s else s
  s=s.replace('</body>','<script src="/professional.js?v=20261004" defer></script></body>') if '/professional.js' not in s else s
  s=re.sub(r'/script.js\?v=[^" ]+','/script.js?v=20261004',s)
  if base.startswith('projects/'):
   s=s.replace('href="/contact.html">گفت‌وگو درباره سفارش مشابه','href="/contact.html?project='+Path(base).stem+'#inquiry">گفت‌وگو درباره سفارش مشابه')
 p.write_text(s,encoding='utf8')
ET.register_namespace('','http://www.sitemaps.org/schemas/sitemap/0.9');tree=ET.Element('{http://www.sitemaps.org/schemas/sitemap/0.9}urlset')
for p in sorted(R.rglob('*.html')):
 rel=p.relative_to(R).as_posix()
 if rel=='404.html':continue
 path=rel[:-10] if rel.endswith('index.html') else rel
 ET.SubElement(ET.SubElement(tree,'url'),'loc').text=B+'/'+path
ET.ElementTree(tree).write(R/'sitemap.xml',encoding='utf-8',xml_declaration=True)
print('Built English edition and reciprocal language links')
